### PR TITLE
fix cluster error

### PR DESCRIPTION
**Pull request by coolfile**
fix cluster error in some device

### CODE REVIEW

**Comment by coolfile** [comment]
for the first commit, i read Microsoft FAT Specification Section 4.1, FAT32 cluster need and 0x0FFFFFFF.
the second commit, mmm, This is really not a good idea

**Comment by magnusja** [comment]
So in what case did you have problems with the cluster address?

Yep it is not :D

**Comment by coolfile** [comment]
i used this for android otg and meet two crash

**Comment by coolfile** [comment]
i used this for android otg and meet two crash
first:
```
java.lang.ArrayIndexOutOfBoundsException length=82; index=82
com.github.mjdev.libaums.fs.fat32.ClusterChain.read(ClusterChain.java:112)
com.github.mjdev.libaums.fs.fat32.FatFile.read(FatFile.java:159)
```
debug  and find error cluster 0x50000145

second:
```
java.io.IOException Could not write to device, result == -1 errno 88 Socket operation on non-socket
com.github.mjdev.libaums.usb.JellyBeanMr2Communication.bulkOutTransfer(JellyBeanMr2Communication.java:45)
com.github.mjdev.libaums.driver.scsi.ScsiBlockDevice.transferCommand(ScsiBlockDevice.java:143)
com.github.mjdev.libaums.driver.scsi.ScsiBlockDevice.write(ScsiBlockDevice.java:230)
com.github.mjdev.libaums.driver.ByteBlockDevice.write(ByteBlockDevice.java:117)
com.github.mjdev.libaums.fs.fat32.ClusterChain.write(ClusterChain.java:160)
com.github.mjdev.libaums.fs.fat32.FatDirectory.write(FatDirectory.java:321)
com.github.mjdev.libaums.fs.fat32.FatFile.flush(FatFile.java:176)
com.github.mjdev.libaums.fs.fat32.FatFile.close(FatFile.java:181)
com.github.mjdev.libaums.fs.UsbFileInputStream.close(UsbFileInputStream.java:68)
```
so i changed UsbFileInputStream close()

**Comment by magnusja** [comment]
> i used this for android otg and meet two crash
> first:
> 
> ```
> java.lang.ArrayIndexOutOfBoundsException length=82; index=82
> com.github.mjdev.libaums.fs.fat32.ClusterChain.read(ClusterChain.java:112)
> com.github.mjdev.libaums.fs.fat32.FatFile.read(FatFile.java:159)
> ```
> 
> debug and find error cluster 0x50000145

Interesting, any specific device this occurs? Is your pen drive unusually large maybe? I have never had this problem an tested drives up to 500 GB.

> 
> second:
> 
> ```
> java.io.IOException Could not write to device, result == -1 errno 88 Socket operation on non-socket
> com.github.mjdev.libaums.usb.JellyBeanMr2Communication.bulkOutTransfer(JellyBeanMr2Communication.java:45)
> com.github.mjdev.libaums.driver.scsi.ScsiBlockDevice.transferCommand(ScsiBlockDevice.java:143)
> com.github.mjdev.libaums.driver.scsi.ScsiBlockDevice.write(ScsiBlockDevice.java:230)
> com.github.mjdev.libaums.driver.ByteBlockDevice.write(ByteBlockDevice.java:117)
> com.github.mjdev.libaums.fs.fat32.ClusterChain.write(ClusterChain.java:160)
> com.github.mjdev.libaums.fs.fat32.FatDirectory.write(FatDirectory.java:321)
> com.github.mjdev.libaums.fs.fat32.FatFile.flush(FatFile.java:176)
> com.github.mjdev.libaums.fs.fat32.FatFile.close(FatFile.java:181)
> com.github.mjdev.libaums.fs.UsbFileInputStream.close(UsbFileInputStream.java:68)
> ```
> 
> so i changed UsbFileInputStream close()

Yeah this is a common error when writing unfortunately, but I do not know what is causing this :/ Usually replugging the usb drive works best. Did you only encounter this in the `close()` method so far?

**Comment by coolfile** [comment]
first:
I am using an 8GB USB flash drive, and this happens occasionally. for the cluster address 0x50000145 the correct is 0x00000145, The highest bit is useless.
second:
it's my code. i read the data from the USB flash drive. When I unplug it, it crashed in close()
```
    var out: BufferedOutputStream? = null
    var inputStream: UsbFileInputStream? = null
    try {
        out = BufferedOutputStream(FileOutputStream(to))
        inputStream = UsbFileInputStream(from)
        val bytes = ByteArray(32 * 1024)
        var count: Int
        while (true) {
            count = inputStream.read(bytes)
            if (count == -1) {
                break
            }
            out.write(bytes, 0, count)
            sum += count
        }
    } catch (e: IOException) {
        e("otg File error copying!")
    } finally {
        out?.close()
        inputStream?.close()
    }
```

**Comment by coolfile** [comment]
I thought about another solution. `FatFile.close()` do nothing, `UsbFileOutputStream` call `FatFile.flush()` before `close()`, `UsbFileIntputStream` do not call `FatFile.flush()`

**Comment by magnusja** [comment]
Hmm that works properly? I am actually confused that it does not cause the same problems because you are still flushing right? Just at a different place in code.

What might happen here is that the correct length of the file is not written to disk because you are settings the length after the flush.

In addition this would be an API change which breaks existing code if someone is using only the `UsbFile` API to write and not the `OutputStream`.

**Comment by magnusja** [comment]
Another thing: from the example code you showed I get the impression that you are only reading from the USB device but I guess to problem is when writing to the USB right?

**Comment by coolfile** [comment]
i only read from USB device in my case, but when i close inputstream, it call `flush()` and crash
```
java.io.IOException Could not write to device, result == -1 errno 88 Socket operation on non-socket
com.github.mjdev.libaums.usb.JellyBeanMr2Communication.bulkOutTransfer(JellyBeanMr2Communication.java:45)
com.github.mjdev.libaums.driver.scsi.ScsiBlockDevice.transferCommand(ScsiBlockDevice.java:143)
com.github.mjdev.libaums.driver.scsi.ScsiBlockDevice.write(ScsiBlockDevice.java:230)
com.github.mjdev.libaums.driver.ByteBlockDevice.write(ByteBlockDevice.java:117)
com.github.mjdev.libaums.fs.fat32.ClusterChain.write(ClusterChain.java:160)
com.github.mjdev.libaums.fs.fat32.FatDirectory.write(FatDirectory.java:321)
com.github.mjdev.libaums.fs.fat32.FatFile.flush(FatFile.java:176)
com.github.mjdev.libaums.fs.fat32.FatFile.close(FatFile.java:181)
com.github.mjdev.libaums.fs.UsbFileInputStream.close(UsbFileInputStream.java:68)
```
So I thought the `UsbFileInputstream` shouldn’t call `FatFile.flush()`

**Comment by coolfile** [comment]
it's break `UsbFile` API, sry, I did not think about it.

**Comment by magnusja** [comment]
Okay I am a little confused. In the PR you changed `UsbFileOutputStream` which is for writing. 

`UsbFileInputStream` class flush/close because otherwise the last accessed time is not getting written to disk.

**Comment by coolfile** [comment]
> Okay I am a little confused. In the PR you changed `UsbFileOutputStream` which is for writing.
> 
> `UsbFileInputStream` class flush/close because otherwise the last accessed time is not getting written to disk.

oh, I know. i will `catch()` this exception in the `finally()` and close this PR.

**Comment by magnusja** [comment]
If you want you can still open a PR with the fix for the cluster address, I will merge that then.

**Pull request closed without merging**
