### PR TITLE
QEMU instrumented tests

### PR DESCRIPTION
**Pull request by Depau**
WIP branch to add instrumented tests.

Since there are already tests in the `app` module, I'll move them to the `libaums` module in the `androidTest` source set and remove all testing code from the app, which will become a simple demo of the library.

### CODE REVIEW

**Comment by Depau** [comment]
All the Java/Kotlin instrumented tests have been converted from Java to Kotlin (which helped me spot some null-safety issues, but otherwise nice to have, not really required) and moved from the demo app to... `libusbcommunication`.

I'd like your comment on this because I feel like this is a very, very nasty solution but I couldn't come up with a better idea. This is required since I also made the tests parametric, the tests are run with all communications including libusb.

This means that if I were to move them to the `libaums` module, that would create a circular dependency since `libaums:androidTest` depends on `libusbcommunication` which depends on `libaums`; Gradle isn't very happy about this.

Otherwise pretty much everything works when running the tests from Android Studio, both on real devices and on QEMU. I wasn't able to run them manually with gradle but I'm gonna check that now, and also fix the travis build failing.

I've got some nasty scripts ready to bring up a workable Android VM, I'll test them soon with `qemu-headless` on the various CIs and integrate them. (reminder: we need Android x86 and not the official emulator since emulated USB is broken in the latter)

**Comment by Depau** [comment]
Okay, this is ready for review.

Remarks:

- Tests work consistently on both real devices and QEMU: `./gradlew androidtests:connectedAndroidTest`
- Tests were moved from the demo app into the new `androidtests` module to allow for also testing the libusb communication without creating dependency loops
- We have a small problem: apparently there is no way to automatically grant the USB permission. I worked around it by waiting in a loop for it and printing some "unique" tokens in logcat so that in the CI we can have it approved by an external program.

**Comment by magnusja** [comment]
Hey there,

first of all thanks a lot for your contributions! Love it!
Sorry for the late response I was on vacation the last weeks.

This looks great, the only comment I would have is that what is been tested now is only a minor part, it might make sense to move.copy some of the FAT32 unit tests, right?

**Comment by Depau** [comment]
> it might make sense to move.copy some of the FAT32 unit tests, right?

Sure.

I would also like to have some block device tests, maybe I can figure something out. In my wrapper i do some tests that write a pseudo random pattern and try to read it back, I'll see if i can pull off something without using the wrapper but with just reflection.

**Pull request merged**
