### PR TITLE
Don't try to initialize partitions if there is no MBR on the device.

### PR DESCRIPTION
**Pull request by mrolcsi**
Catches a `NullPointerException`.

### CODE REVIEW

**Comment by magnusja** [comment]
Didn't you say that this bug is already fixed on develop?

**Comment by mrolcsi** [comment]
Yes, but this is a fix for the master branch.

Never mind, I'll just use the develop branch then.

**Comment by magnusja** [comment]
Very sorry, it wasn't clear to me that you are still preparing a PR after you mentioned that. I hope it didn't take too much time.
I will ping you when I release a new version so that you can switch to the stable branch again, if you like.

**Comment by mrolcsi** [comment]
It's alright. It's a pretty easy fix, I was just busy with other stuff.

Yeah, I'd appreciate that, thanks!

**Pull request closed without merging**
