### PR TITLE
Fix Gradle build with latest build tools

### LINKED ISSUE #138: A failure occurred while executing com.android.build.gradle.internal.transforms.JacocoTransform$JacocoWorkerAction in andriod studio 3.1
PLEASE NOTE:
Before creating an issue, please think about wheter you are really reporting an issue or just have a question/problem. The latter are better suited for Stackoverflow or gitter (https://gitter.im/libaums). The best approach for a question or problem regarding libaums is to ask on Stackoverflow and hint me to the question via gitter!

If you are sure that you would like to open an issue, please delete all of this message and continue. 
Thank you!

### PR DESCRIPTION
**Pull request by Depau**
Fixes a lot of issues with Gradle.

Closes #138

### CODE REVIEW

**Comment by Depau** [comment]
It still doesn't build because some tests fail. Some fail because they create more than 4GB of temporary files, filling up `/tmp` on my machine, one fails because the file you provide in the Dropbox JSON now returns HTTP 403. Could you please check that?

**Comment by magnusja** [comment]
Which file exactly?

**Comment by Depau** [comment]
http://trailers.divx.com/divx_prod/profiles/WiegelesHeliSki_DivXPlus_19Mbps.mkv

**Comment by magnusja** [comment]
Access denied

**Comment by Depau** [comment]
I know. That file is being accessed by the tests in the library. Because the URL is not available, tests are failing.

**Pull request merged**
